### ISSUE TITLE
CoIMS support for Android Go

### ISSUE THREAD

**Issue by 9600** [herlesupreeth/CoIMS_Wiki#4]
I wondered if it might be possible to add support to CoIMS for Android Go. Looks as though it should just require declaration of: 

<uses-feature android:name="android.hardware.ram.low" android:required="true">

https://developer.android.com/google/play/publishing/multiple-apks#SupportedFilters

**Comment by herlesupreeth** [comment]
I have pushed the new version of the CoIMS app with support for Android Go, let me know if it installs on Android Go devices. Thanks for all the help.

**Comment by herlesupreeth** [comment]
The new version is now available in  google play store, please give it a try

**Comment by 9600** [comment]
Many thanks!

I've search for it in the Play store on the Go handset and it doesn't appear. If I follow the link from the README I still get a message "Your device isn't compatible with this version." Is there anywhere I can download an APK to try with adb install?

**Comment by herlesupreeth** [comment]
Thats a bit strange. Can you re-verify that from play store that the app version is 0.7?

Eitherway, I will provide you the apk on Monday.

**Comment by 9600** [comment]
Strangely, it doesn't seem to show the current version in App info with Play in Google Go. There's less info than with regular Android and I can see the January release date, but not Version or Updated on.

**Comment by herlesupreeth** [comment]
Ah i see. Does that Android go device run Android Pie or above? If not the app won't be compatible with the device as this app requires atleast Android Pie.

Btw, i found 0.5 version of my app published in the link below, you can use that

https://m.apkpure.com/coims/com.sherle.coims

**Comment by 9600** [comment]
Right, that looks to be the problem then, it's running 8.1.0.

**Comment by herlesupreeth** [comment]
Ah, i see. Unfortunately i cannot support older Android versions.

**Comment by 9600** [comment]
Thanks for all your help, it's much appreciated.

**Comment by herlesupreeth** [comment]
I managed to support Android 8.0 and above devices. Please try it out on that Android Go device. Please let me know how it goes. Btw, you wont see Carrier ID in Android 8.0 and 8.1 devices as the API doesnt have that function

**Comment by 9600** [comment]
Many thanks, I could now see CoIMS in the Play Store when I searched with the J4 Core/Android Go device, and proceed to install this successfully. However, I get an error when it starts up (with the ARA-M provisioned SIM installed).
![Screenshot_20200421-082125](https://user-images.githubusercontent.com/233314/79841139-e3588980-83ae-11ea-8d4e-27a40b214e01.jpg)

**Comment by herlesupreeth** [comment]
Thank you for testing it. Can you please try with the apk attached below and let me know if that works?
[app-release.zip](https://github.com/herlesupreeth/CoIMS_Wiki/files/4510014/app-release.zip)

**Comment by 9600** [comment]
I get the same error on starting CoIMS, but this time I checked and I can go into Testing Mode and Samsung IMS Settings without any problems. Well, in the latter I get an ISIM error, but I think I got this before and it's expected.

**Comment by herlesupreeth** [comment]
Can you please send me a screenshot of the error?

**Comment by 9600** [comment]
![Screenshot_20200421-140821](https://user-images.githubusercontent.com/233314/79869736-bec5d700-83d9-11ea-9787-01b05316a8a6.jpg)

![Screenshot_20200421-140830](https://user-images.githubusercontent.com/233314/79869749-c2595e00-83d9-11ea-9365-a9ca42c74d85.jpg)

**Comment by herlesupreeth** [comment]
Thanks a lot for all you help. Can you please give one last try with the apk attached and let me know how it goes?
[app-release.zip](https://github.com/herlesupreeth/CoIMS_Wiki/files/4510178/app-release.zip)

**Comment by 9600** [comment]
With this version it exits immediately and says "CoIMS has stopped".

**Comment by herlesupreeth** [comment]
okay, thanks for testing. Can you please try one last version of this?
[app-release.zip](https://github.com/herlesupreeth/CoIMS_Wiki/files/4510309/app-release.zip)

**Comment by 9600** [comment]
![Screenshot_20200421-144013](https://user-images.githubusercontent.com/233314/79872847-35fd6a00-83de-11ea-98f8-72166afccebd.jpg)

**Comment by herlesupreeth** [comment]
Thanks once again for testing. This morning i released another update (v0.9) with the bug fix for Android 8.0 and 8.1 devices. And btw, for Samsung devices you need to activate using Samsung IMS settings option in the menu and set appropriate IMS settings

**Comment by 9600** [comment]
Thanks, Supreeth, much appreciated! Just installed via Play Store and this now starts up fine. 

It may be later this week or early next before I can test with the local network again, but this time I should have the J4 Core with Android Go now with CoIMS, a Oneplus 5T, and a Oneplus One (with LineageOS loaded). The 5T was just given to me and I had to get a Nano->Micro SIM adapter for the Oneplus One (quite old, so maybe not the best to try and get VoLTE working on).

I'll let you know how I get on.

**Comment by herlesupreeth** [comment]
Nice.. thanks a lot

**Comment by herlesupreeth** [comment]
i would like to close this issue as you mentioned that it works on Android Go devices. Please feel free to re-open this issue if there is any problem
